["delay_1"]
  left  = 0.015
  right = 0.0
  room  = 0.15
  wet   = 1.0

[delay_2]
  left  = 0.44
  right = 0.14
  room  = 1.0
  wet   = 0.22

[delay_3]
  left  = 0.8
  right = 0.2
  room  = 0.2
  wet   = 0.9

[delay_4]
  left  = 0.44
  right = 0.1
  room  = 0.4
  wet   = 0.1 

[delay_5]
  left  = 0.44
  right = 0.1
  room  = 0.4
  wet   = 0.1

[delay_6]
  left  = 0.44
  right = 0.1
  room  = 0.4
  wet   = 0.1     

["mixer_1"] 
  vol= 0.85  
  pan= 0.0

[mixer_2] 
  vol= 0.85  
  pan= 1.0

[mixer_3] 
  vol= 0.4  
  pan= 0.35

[mixer_4] 
  vol= 0.6  
  pan= 0.35 

[mixer_5] 
  vol= 0.6  
  pan= 0.5

[mixer_6]
  vol= 0.1
  pan= 0.75  

